/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return a simple liveness payload.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_transactions_get"];
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_api_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Transactions */
        get: operations["export_transactions_api_transactions_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/import-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Transactions */
        post: operations["import_transactions_api_transactions_import_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transaction Tags */
        get: operations["list_transaction_tags_api_transactions__transaction_id__tags_get"];
        /** Set Tags */
        put: operations["set_tags_api_transactions__transaction_id__tags_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach Tag */
        post: operations["attach_tag_api_transactions__transaction_id__tags__tag_id__post"];
        /** Detach Tag */
        delete: operations["detach_tag_api_transactions__transaction_id__tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_api_transactions__transaction_id__get"];
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["delete_transaction_api_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        /** Update Transaction */
        patch: operations["update_transaction_api_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Monthly */
        get: operations["get_monthly_api_dashboard_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/treemap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Treemap */
        get: operations["get_treemap_api_dashboard_treemap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calendar */
        get: operations["get_calendar_api_dashboard_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/sankey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sankey */
        get: operations["get_sankey_api_dashboard_sankey_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/balance-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Balance History */
        get: operations["get_balance_history_api_dashboard_balance_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Budgets */
        get: operations["list_budgets_api_budgets_get"];
        put?: never;
        /** Create Budget */
        post: operations["create_budget_api_budgets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress */
        get: operations["get_progress_api_budgets_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{budget_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Budget */
        get: operations["get_budget_api_budgets__budget_id__get"];
        put?: never;
        post?: never;
        /** Delete Budget */
        delete: operations["delete_budget_api_budgets__budget_id__delete"];
        options?: never;
        head?: never;
        /** Update Budget */
        patch: operations["update_budget_api_budgets__budget_id__patch"];
        trace?: never;
    };
    "/api/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recurring */
        get: operations["list_recurring_api_recurring_get"];
        put?: never;
        /** Create Recurring */
        post: operations["create_recurring_api_recurring_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recurring/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Recurring */
        post: operations["run_recurring_api_recurring_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recurring/{recurring_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recurring */
        get: operations["get_recurring_api_recurring__recurring_id__get"];
        put?: never;
        post?: never;
        /** Delete Recurring */
        delete: operations["delete_recurring_api_recurring__recurring_id__delete"];
        options?: never;
        head?: never;
        /** Update Recurring */
        patch: operations["update_recurring_api_recurring__recurring_id__patch"];
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_api_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tag */
        get: operations["get_tag_api_tags__tag_id__get"];
        put?: never;
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_api_tags__tag_id__delete"];
        options?: never;
        head?: never;
        /** Update Tag */
        patch: operations["update_tag_api_tags__tag_id__patch"];
        trace?: never;
    };
    "/api/savings-goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_api_savings_goals_get"];
        put?: never;
        /** Create Goal */
        post: operations["create_goal_api_savings_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/savings-goals/{goal_id}/contribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Contribute */
        post: operations["contribute_api_savings_goals__goal_id__contribute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/savings-goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal */
        get: operations["get_goal_api_savings_goals__goal_id__get"];
        put?: never;
        post?: never;
        /** Delete Goal */
        delete: operations["delete_goal_api_savings_goals__goal_id__delete"];
        options?: never;
        head?: never;
        /** Update Goal */
        patch: operations["update_goal_api_savings_goals__goal_id__patch"];
        trace?: never;
    };
    "/api/categorization-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_categorization_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_categorization_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization-rules/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest */
        get: operations["suggest_api_categorization_rules_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule */
        get: operations["get_rule_api_categorization_rules__rule_id__get"];
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_categorization_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Rule */
        patch: operations["update_rule_api_categorization_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/reports/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Pdf */
        get: operations["download_pdf_api_reports_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Backup */
        get: operations["download_backup_api_backup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Backup */
        post: operations["restore_backup_api_backup_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountRead */
        AccountRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            type: components["schemas"]["AccountType"];
            /** Currency */
            currency: string;
            /** Initial Balance */
            initial_balance: string;
            /** Archived */
            archived: boolean;
        };
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "cash" | "bank" | "card" | "savings";
        /**
         * BalancePoint
         * @description Single point in the balance history chart.
         */
        BalancePoint: {
            /** Date */
            date: string;
            /** Balance */
            balance: number;
        };
        /** Body_import_transactions_api_transactions_import_csv_post */
        Body_import_transactions_api_transactions_import_csv_post: {
            /** File */
            file: string;
        };
        /** Body_restore_backup_api_backup_restore_post */
        Body_restore_backup_api_backup_restore_post: {
            /** File */
            file: string;
        };
        /** BudgetCreate */
        BudgetCreate: {
            /** Category Id */
            category_id: number;
            /** Amount */
            amount: number | string;
            period: components["schemas"]["BudgetPeriod"];
        };
        /**
         * BudgetPeriod
         * @enum {string}
         */
        BudgetPeriod: "monthly" | "yearly";
        /** BudgetProgress */
        BudgetProgress: {
            /** Id */
            id: number;
            /** Category Id */
            category_id: number;
            /** Category Name */
            category_name: string;
            /** Category Color */
            category_color: string | null;
            /** Amount */
            amount: string;
            period: components["schemas"]["BudgetPeriod"];
            /** Spent */
            spent: string;
            /** Remaining */
            remaining: string;
            /** Percentage */
            percentage: number;
            /** Exceeded */
            exceeded: boolean;
        };
        /** BudgetRead */
        BudgetRead: {
            /** Id */
            id: number;
            /** Category Id */
            category_id: number;
            /** Amount */
            amount: string;
            period: components["schemas"]["BudgetPeriod"];
        };
        /** BudgetUpdate */
        BudgetUpdate: {
            /** Amount */
            amount?: number | string | null;
            period?: components["schemas"]["BudgetPeriod"] | null;
        };
        /** CategorizationRuleCreate */
        CategorizationRuleCreate: {
            /** Pattern */
            pattern: string;
            /** Category Id */
            category_id: number;
            /** Subcategory Id */
            subcategory_id?: number | null;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** CategorizationRuleRead */
        CategorizationRuleRead: {
            /** Id */
            id: number;
            /** Pattern */
            pattern: string;
            /** Category Id */
            category_id: number;
            /** Subcategory Id */
            subcategory_id: number | null;
            /** Priority */
            priority: number;
            /** Enabled */
            enabled: boolean;
        };
        /** CategorizationRuleUpdate */
        CategorizationRuleUpdate: {
            /** Pattern */
            pattern?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** Subcategory Id */
            subcategory_id?: number | null;
            /** Priority */
            priority?: number | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * CategoryAmount
         * @description Total amount aggregated for a single category in a period.
         */
        CategoryAmount: {
            /** Category Id */
            category_id: number | null;
            /** Name */
            name: string;
            /** Color */
            color: string | null;
            /** Total */
            total: string;
        };
        /** CategoryRead */
        CategoryRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            type: components["schemas"]["CategoryType"];
            /** Parent Id */
            parent_id: number | null;
            /** Color */
            color: string | null;
            /** Icon */
            icon: string | null;
        };
        /**
         * CategoryType
         * @enum {string}
         */
        CategoryType: "income" | "expense";
        /**
         * DashboardSummary
         * @description KPIs and per-category breakdowns for a given period.
         */
        DashboardSummary: {
            /** Year */
            year: number;
            /** Month */
            month: number | null;
            /** Income */
            income: string;
            /** Expense */
            expense: string;
            /** Balance */
            balance: string;
            /** Income Change */
            income_change?: number | null;
            /** Expense Change */
            expense_change?: number | null;
            /** Balance Change */
            balance_change?: number | null;
            /** Expense By Category */
            expense_by_category: components["schemas"]["CategoryAmount"][];
            /** Income By Category */
            income_by_category: components["schemas"]["CategoryAmount"][];
        };
        /**
         * DayAmount
         * @description Daily expense total for the calendar heatmap.
         */
        DayAmount: {
            /** Day */
            day: string;
            /** Value */
            value: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Imported */
            imported: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors: string[];
        };
        /**
         * MonthlyStats
         * @description Income, expense and cumulative balance for a single month.
         */
        MonthlyStats: {
            /** Month */
            month: number;
            /** Income */
            income: string;
            /** Expense */
            expense: string;
            /** Balance */
            balance: string;
            /** Cumulative Balance */
            cumulative_balance: string;
        };
        /**
         * RecurrenceFrequency
         * @enum {string}
         */
        RecurrenceFrequency: "daily" | "weekly" | "monthly" | "yearly";
        /** RecurringCreate */
        RecurringCreate: {
            type: components["schemas"]["TransactionType"];
            /** Concept */
            concept: string;
            /** Description */
            description?: string | null;
            /** Amount */
            amount: number | string;
            /** Category Id */
            category_id?: number | null;
            /** Subcategory Id */
            subcategory_id?: number | null;
            /** Account Id */
            account_id: number;
            /** Transfer Account Id */
            transfer_account_id?: number | null;
            frequency: components["schemas"]["RecurrenceFrequency"];
            /**
             * Interval
             * @default 1
             */
            interval: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
        };
        /** RecurringRead */
        RecurringRead: {
            /** Id */
            id: number;
            type: components["schemas"]["TransactionType"];
            /** Concept */
            concept: string;
            /** Description */
            description: string | null;
            /** Amount */
            amount: string;
            /** Category Id */
            category_id: number | null;
            /** Subcategory Id */
            subcategory_id: number | null;
            /** Account Id */
            account_id: number;
            /** Transfer Account Id */
            transfer_account_id: number | null;
            frequency: components["schemas"]["RecurrenceFrequency"];
            /** Interval */
            interval: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /**
             * Next Run Date
             * Format: date
             */
            next_run_date: string;
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RecurringRunResult */
        RecurringRunResult: {
            /** Generated */
            generated: number;
        };
        /**
         * RecurringUpdate
         * @description Partial update. Only fields present in the request are applied.
         */
        RecurringUpdate: {
            /** Concept */
            concept?: string | null;
            /** Description */
            description?: string | null;
            /** Amount */
            amount?: number | string | null;
            /** Category Id */
            category_id?: number | null;
            /** Subcategory Id */
            subcategory_id?: number | null;
            /** Account Id */
            account_id?: number | null;
            /** Transfer Account Id */
            transfer_account_id?: number | null;
            frequency?: components["schemas"]["RecurrenceFrequency"] | null;
            /** Interval */
            interval?: number | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Active */
            active?: boolean | null;
        };
        /**
         * SankeyData
         * @description Full Sankey diagram: nodes + links.
         */
        SankeyData: {
            /** Nodes */
            nodes: components["schemas"]["SankeyNode"][];
            /** Links */
            links: components["schemas"]["SankeyLink"][];
        };
        /**
         * SankeyLink
         * @description Directed link between two Sankey nodes.
         */
        SankeyLink: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Value */
            value: number;
        };
        /**
         * SankeyNode
         * @description Node in the Sankey diagram.
         */
        SankeyNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** SavingsGoalContribute */
        SavingsGoalContribute: {
            /** Amount */
            amount: number | string;
        };
        /** SavingsGoalCreate */
        SavingsGoalCreate: {
            /** Name */
            name: string;
            /** Target Amount */
            target_amount: number | string;
            /**
             * Current Amount
             * @default 0
             */
            current_amount: number | string;
            /** Deadline */
            deadline?: string | null;
            /** Color */
            color?: string | null;
        };
        /** SavingsGoalRead */
        SavingsGoalRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Target Amount */
            target_amount: string;
            /** Current Amount */
            current_amount: string;
            /** Deadline */
            deadline: string | null;
            /** Color */
            color: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Progress Pct */
            progress_pct: number;
            /** Is Completed */
            is_completed: boolean;
            /** Days Remaining */
            days_remaining: number | null;
        };
        /** SavingsGoalUpdate */
        SavingsGoalUpdate: {
            /** Name */
            name?: string | null;
            /** Target Amount */
            target_amount?: number | string | null;
            /** Current Amount */
            current_amount?: number | string | null;
            /** Deadline */
            deadline?: string | null;
            /** Color */
            color?: string | null;
        };
        /**
         * SuggestResponse
         * @description Returned by the suggest endpoint when a rule matches.
         */
        SuggestResponse: {
            /** Rule Id */
            rule_id: number;
            /** Category Id */
            category_id: number;
            /** Subcategory Id */
            subcategory_id: number | null;
        };
        /** TagCreate */
        TagCreate: {
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
        };
        /** TagRead */
        TagRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Color */
            color: string | null;
        };
        /** TagUpdate */
        TagUpdate: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            type: components["schemas"]["TransactionType"];
            /** Concept */
            concept: string;
            /** Description */
            description?: string | null;
            /** Amount */
            amount: number | string;
            /** Category Id */
            category_id?: number | null;
            /** Subcategory Id */
            subcategory_id?: number | null;
            /** Account Id */
            account_id: number;
            /** Transfer Account Id */
            transfer_account_id?: number | null;
        };
        /** TransactionRead */
        TransactionRead: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            type: components["schemas"]["TransactionType"];
            /** Concept */
            concept: string;
            /** Description */
            description: string | null;
            /** Amount */
            amount: string;
            /** Category Id */
            category_id: number | null;
            /** Subcategory Id */
            subcategory_id: number | null;
            /** Account Id */
            account_id: number;
            /** Transfer Account Id */
            transfer_account_id: number | null;
            /** Recurring Id */
            recurring_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["TagRead"][];
        };
        /**
         * TransactionType
         * @enum {string}
         */
        TransactionType: "income" | "expense" | "transfer";
        /**
         * TransactionUpdate
         * @description Partial update. Only fields present in the request are applied.
         */
        TransactionUpdate: {
            /** Date */
            date?: string | null;
            type?: components["schemas"]["TransactionType"] | null;
            /** Concept */
            concept?: string | null;
            /** Description */
            description?: string | null;
            /** Amount */
            amount?: number | string | null;
            /** Category Id */
            category_id?: number | null;
            /** Subcategory Id */
            subcategory_id?: number | null;
            /** Account Id */
            account_id?: number | null;
            /** Transfer Account Id */
            transfer_account_id?: number | null;
        };
        /**
         * TreemapBranch
         * @description Branch node (category) for the treemap; may contain leaf children.
         */
        TreemapBranch: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["TreemapLeaf"][];
            /** Value */
            value?: number | null;
        };
        /**
         * TreemapData
         * @description Root node for the expense treemap.
         */
        TreemapData: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Children */
            children: components["schemas"]["TreemapBranch"][];
        };
        /**
         * TreemapLeaf
         * @description Leaf node (subcategory or category without subcategories) for the treemap.
         */
        TreemapLeaf: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"][];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"][];
                };
            };
        };
    };
    list_transactions_api_transactions_get: {
        parameters: {
            query?: {
                year?: number | null;
                month?: number | null;
                limit?: number | null;
                type?: components["schemas"]["TransactionType"] | null;
                category_id?: number | null;
                account_id?: number | null;
                tag_id?: number | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_api_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_transactions_api_transactions_export_get: {
        parameters: {
            query?: {
                year?: number | null;
                month?: number | null;
                type?: components["schemas"]["TransactionType"] | null;
                category_id?: number | null;
                account_id?: number | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_transactions_api_transactions_import_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_transactions_api_transactions_import_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transaction_tags_api_transactions__transaction_id__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tags_api_transactions__transaction_id__tags_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": number[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_tag_api_transactions__transaction_id__tags__tag_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detach_tag_api_transactions__transaction_id__tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_api_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_api_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_api_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_dashboard_summary_get: {
        parameters: {
            query?: {
                year?: number | null;
                month?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_monthly_api_dashboard_monthly_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_treemap_api_dashboard_treemap_get: {
        parameters: {
            query?: {
                year?: number | null;
                month?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreemapData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_api_dashboard_calendar_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayAmount"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sankey_api_dashboard_sankey_get: {
        parameters: {
            query?: {
                year?: number | null;
                month?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SankeyData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_balance_history_api_dashboard_balance_history_get: {
        parameters: {
            query?: {
                period?: "1M" | "3M" | "1A" | "5A";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalancePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_budgets_api_budgets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetRead"][];
                };
            };
        };
    };
    create_budget_api_budgets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_api_budgets_progress_get: {
        parameters: {
            query: {
                year: number;
                month?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetProgress"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_budget_api_budgets__budget_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_budget_api_budgets__budget_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_budget_api_budgets__budget_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recurring_api_recurring_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRead"][];
                };
            };
        };
    };
    create_recurring_api_recurring_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_recurring_api_recurring_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRunResult"];
                };
            };
        };
    };
    get_recurring_api_recurring__recurring_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurring_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recurring_api_recurring__recurring_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurring_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recurring_api_recurring__recurring_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurring_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRead"][];
                };
            };
        };
    };
    create_tag_api_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tag_api_tags__tag_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_api_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_api_savings_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalRead"][];
                };
            };
        };
    };
    create_goal_api_savings_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contribute_api_savings_goals__goal_id__contribute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoalContribute"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goal_api_savings_goals__goal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_goal_api_savings_goals__goal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_goal_api_savings_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_categorization_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorizationRuleRead"][];
                };
            };
        };
    };
    create_rule_api_categorization_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategorizationRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorizationRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_api_categorization_rules_suggest_get: {
        parameters: {
            query: {
                concept: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_api_categorization_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorizationRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_categorization_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_categorization_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategorizationRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorizationRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_pdf_api_reports_pdf_get: {
        parameters: {
            query: {
                year: number;
                month?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_backup_api_backup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    restore_backup_api_backup_restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_restore_backup_api_backup_restore_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
