/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return a simple liveness payload.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_transactions_get"];
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_api_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_api_transactions__transaction_id__get"];
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["delete_transaction_api_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        /** Update Transaction */
        patch: operations["update_transaction_api_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountRead */
        AccountRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            type: components["schemas"]["AccountType"];
            /** Currency */
            currency: string;
            /** Initial Balance */
            initial_balance: string;
            /** Archived */
            archived: boolean;
        };
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "cash" | "bank" | "card" | "savings";
        /**
         * CategoryAmount
         * @description Total amount aggregated for a single category in a period.
         */
        CategoryAmount: {
            /** Category Id */
            category_id: number | null;
            /** Name */
            name: string;
            /** Color */
            color: string | null;
            /** Total */
            total: string;
        };
        /** CategoryRead */
        CategoryRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            type: components["schemas"]["CategoryType"];
            /** Parent Id */
            parent_id: number | null;
            /** Color */
            color: string | null;
            /** Icon */
            icon: string | null;
        };
        /**
         * CategoryType
         * @enum {string}
         */
        CategoryType: "income" | "expense";
        /**
         * DashboardSummary
         * @description KPIs and per-category breakdowns for a given period.
         */
        DashboardSummary: {
            /** Year */
            year: number;
            /** Month */
            month: number | null;
            /** Income */
            income: string;
            /** Expense */
            expense: string;
            /** Balance */
            balance: string;
            /** Expense By Category */
            expense_by_category: components["schemas"]["CategoryAmount"][];
            /** Income By Category */
            income_by_category: components["schemas"]["CategoryAmount"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** TransactionCreate */
        TransactionCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            type: components["schemas"]["TransactionType"];
            /** Concept */
            concept: string;
            /** Description */
            description?: string | null;
            /** Amount */
            amount: number | string;
            /** Category Id */
            category_id?: number | null;
            /** Subcategory Id */
            subcategory_id?: number | null;
            /** Account Id */
            account_id: number;
        };
        /** TransactionRead */
        TransactionRead: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            type: components["schemas"]["TransactionType"];
            /** Concept */
            concept: string;
            /** Description */
            description: string | null;
            /** Amount */
            amount: string;
            /** Category Id */
            category_id: number | null;
            /** Subcategory Id */
            subcategory_id: number | null;
            /** Account Id */
            account_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TransactionType
         * @enum {string}
         */
        TransactionType: "income" | "expense";
        /**
         * TransactionUpdate
         * @description Partial update. Only fields present in the request are applied.
         */
        TransactionUpdate: {
            /** Date */
            date?: string | null;
            type?: components["schemas"]["TransactionType"] | null;
            /** Concept */
            concept?: string | null;
            /** Description */
            description?: string | null;
            /** Amount */
            amount?: number | string | null;
            /** Category Id */
            category_id?: number | null;
            /** Subcategory Id */
            subcategory_id?: number | null;
            /** Account Id */
            account_id?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"][];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"][];
                };
            };
        };
    };
    list_transactions_api_transactions_get: {
        parameters: {
            query?: {
                year?: number | null;
                month?: number | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_api_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_api_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_api_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_api_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_dashboard_summary_get: {
        parameters: {
            query?: {
                year?: number | null;
                month?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
