"""add transfer support

Revision ID: 366e07275880
Revises: 983a0d728e9c
Create Date: 2026-06-07 20:56:16.091860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "366e07275880"
down_revision: Union[str, Sequence[str], None] = "983a0d728e9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("transfer_account_id", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(length=7),
            type_=sa.Enum("income", "expense", "transfer", name="transactiontype"),
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_transfer_account_id"), ["transfer_account_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_transactions_transfer_account_id", "accounts", ["transfer_account_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_transactions_transfer_account_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_transactions_transfer_account_id"))
        batch_op.alter_column(
            "type",
            existing_type=sa.Enum("income", "expense", "transfer", name="transactiontype"),
            type_=sa.VARCHAR(length=7),
            existing_nullable=False,
        )
        batch_op.drop_column("transfer_account_id")

    # ### end Alembic commands ###
