"""add_balance_adjustments

Revision ID: 72ee8365f3cd
Revises: 8dfb9c3a24eb
Create Date: 2026-10-04 21:17:53.157951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "72ee8365f3cd"
down_revision: Union[str, Sequence[str], None] = "8dfb9c3a24eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balance_adjustments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("balance_adjustments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_balance_adjustments_date"), ["date"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("balance_adjustments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_balance_adjustments_date"))

    op.drop_table("balance_adjustments")
    # ### end Alembic commands ###
