"""add categorization rules

Revision ID: 8dfb9c3a24eb
Revises: 3377f71d086b
Create Date: 2026-06-11 18:33:03.897771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "8dfb9c3a24eb"
down_revision: Union[str, Sequence[str], None] = "3377f71d086b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorization_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("subcategory_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("categorization_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categorization_rules_pattern"), ["pattern"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_categorization_rules_priority"), ["priority"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categorization_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categorization_rules_priority"))
        batch_op.drop_index(batch_op.f("ix_categorization_rules_pattern"))

    op.drop_table("categorization_rules")
    # ### end Alembic commands ###
