"""add recurring transactions

Revision ID: c4ab9a0c7c42
Revises: 32a982c9713b
Create Date: 2026-06-09 20:16:43.635315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "c4ab9a0c7c42"
down_revision: Union[str, Sequence[str], None] = "32a982c9713b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recurring_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("income", "expense", "transfer", name="transactiontype"), nullable=False
        ),
        sa.Column("concept", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("subcategory_id", sa.Integer(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("transfer_account_id", sa.Integer(), nullable=True),
        sa.Column(
            "frequency",
            sa.Enum("daily", "weekly", "monthly", "yearly", name="recurrencefrequency"),
            nullable=False,
        ),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("next_run_date", sa.Date(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_recurring_amount_positive"),
        sa.CheckConstraint("interval > 0", name="ck_recurring_interval_positive"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transfer_account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recurring_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recurring_transactions_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recurring_transactions_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recurring_transactions_next_run_date"), ["next_run_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recurring_transactions_subcategory_id"), ["subcategory_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recurring_transactions_transfer_account_id"),
            ["transfer_account_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_recurring_transactions_type"), ["type"], unique=False)

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("recurring_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_transactions_recurring_id"), ["recurring_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_transactions_recurring_id", "recurring_transactions", ["recurring_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_transactions_recurring_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_transactions_recurring_id"))
        batch_op.drop_column("recurring_id")

    with op.batch_alter_table("recurring_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recurring_transactions_type"))
        batch_op.drop_index(batch_op.f("ix_recurring_transactions_transfer_account_id"))
        batch_op.drop_index(batch_op.f("ix_recurring_transactions_subcategory_id"))
        batch_op.drop_index(batch_op.f("ix_recurring_transactions_next_run_date"))
        batch_op.drop_index(batch_op.f("ix_recurring_transactions_category_id"))
        batch_op.drop_index(batch_op.f("ix_recurring_transactions_account_id"))

    op.drop_table("recurring_transactions")
    # ### end Alembic commands ###
